# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: mail2vdo/otus_dz1
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 80

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  persistence:
    size: 1Gi
  service:
    port: "5432"

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        path: /testrest($|/)(.*)
    - host: arch.homework
      paths:
        path: /otusapp($|/)(.*)
    - host:
      paths:
        path: /testrest($|/)(.*)
  service:
    port: 80

