apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testauth-chart.fullname" . }}
  labels:
    {{- include "testauth-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "testauth-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "testauth-chart.selectorLabels" . | nindent 8 }}
      annotations:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          readinessProbe:
            httpGet:
             port: 9000
             path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
             port: 9000
             path: /health
            initialDelaySeconds: 10
            periodSeconds: 10

